name: "Create Pull Request"
description: "Create a new remote branch and submit a pull request"
inputs:
  branch_name:
    required: true
    description: "The new remote branch to create"
  base_branch:
    required: true
    description: "The base branch to create the the new branch from"
  commit_message:
    required: true
    description: "The commit message"
  commit_user_name:
    required: true
    description: "The GitHub account name used for the commit"
  commit_user_email:
    required: true
    description: "The GitHub account email used for the commit"
  pull_request_body:
    required: true
    description: "The message to include in the pull request body"
  pull_request_title:
    required: true
    description: "The title of the pull request"
  working_directory:
    required: false
    description: "The working directory to run the commands in"
    default: "${{ github.workspace }}"
  github_token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create new Branch and Commit
      run: |
        git checkout -b ${{ inputs.branch_name }}
        git config --global user.name "${{ inputs.commit_user_name }}"
        git config --global user.email "${{ inputs.commit_user_email }}"
        git add -A
        git commit -am "${{ inputs.commit_message }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Push branch to GitHub
      run: |        
        git push --force -u origin ${{ inputs.branch_name }}
      shell: bash
      working-directory:  ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Create Pull Request
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        script: |
          const { repo, owner } = context.repo;
          const existingRequest = await github.rest.pulls.list({
            owner,
            repo,
            base: '${{ inputs.base_branch }}'
          });
          console.log(existingRequest.data.length);
          console.log(existingRequest);
          if (existingRequest.data.length > 0) {
            console.log('Pull request already exists');
            return;
          }
          const result = await github.rest.pulls.create({
            title: '${{ inputs.pull_request_title }}',
            owner,
            repo,
            head: '${{ inputs.branch_name }}',
            base: '${{ inputs.base_branch }}',
            body: '${{ inputs.pull_request_body }}'
          });