name: epac-dev-flow

env:
  pacEnvironment: epac-dev-gh # Change this to a PAC environment name
  definitionsRootFolder: Definitions
  planFolder: Output
  epac_pinned_version: '9.1.5' # set latest or specific version
  az_version: '11.4.0'
  azAccounts_version: '2.19.0'
  azResources_version: '6.16.1'
  azResourceGraph_version: '0.13.0'
 

on:  
  push:    
    branches:      
      - 'test-env-vars'
  workflow_dispatch:

jobs:
  preConfig:
      runs-on: ubuntu-latest
      outputs:
        definitionsRootFolder: ${{ steps.preConfigStep.outputs.definitionsRootFolder }}
        pacEnvironment: ${{ steps.preConfigStep.outputs.pacEnvironment }}
        planFolder: ${{ steps.preConfigStep.outputs.planFolder }}   
        epac_pinned_version: ${{ steps.preConfigStep.outputs.epac_pinned_version }}
        az_version: ${{ steps.preConfigStep.outputs.az_version }}
        azAccounts_version: ${{ steps.preConfigStep.outputs.azAccounts_version }}
        azResources_version: ${{ steps.preConfigStep.outputs.azResources_version }} 
        azResourceGraph_version: ${{ steps.preConfigStep.outputs.azResourceGraph_version }} 
      steps:
        - name: preConfig inputs passed to the reusable workflow
          id: preConfigStep
          run: |
            echo "definitionsRootFolder=$definitionsRootFolder" >> $GITHUB_OUTPUT
            echo "pacEnvironment=$pacEnvironment" >> $GITHUB_OUTPUT
            echo "planFolder=$planFolder" >> $GITHUB_OUTPUT

            echo "epac_pinned_version=$epac_pinned_version"
            echo "epac_pinned_version=$epac_pinned_version" >> $GITHUB_OUTPUT

            echo "az_version=$az_version"
            echo "az_version=$az_version" >> $GITHUB_OUTPUT

            echo "azAccounts_version=$azAccounts_version"
            echo "azAccounts_version=$azAccounts_version" >> $GITHUB_OUTPUT

            echo "azResources_version=$azResources_version"
            echo "azResources_version=$azResources_version" >> $GITHUB_OUTPUT

            echo "azResourceGraph_version=$azResourceGraph_version"
            echo "azResourceGraph_version=$azResourceGraph_version" >> $GITHUB_OUTPUT

  epac-build:
      name: epac build
      needs: [preConfig]
      permissions:
        id-token: write
        contents: read
        pull-requests: write
      uses: ./.github/workflows/job-epac-build.yml
      with:
          definitionsRootFolder: ${{ needs.preConfig.outputs.definitionsRootFolder }}
          pacEnvironment: ${{ needs.preConfig.outputs.pacEnvironment }}
          planFolder: ${{ needs.preConfig.outputs.planFolder }}
          epac_pinned_version: ${{ needs.preConfig.outputs.epac_pinned_version }}
          az_version: ${{ needs.preConfig.outputs.az_version }}
          azAccounts_version: ${{ needs.preConfig.outputs.azAccounts_version }}
          azResources_version: ${{ needs.preConfig.outputs.azResources_version }}
          azResourceGraph_version: ${{ needs.preConfig.outputs.azResourceGraph_version }}
      secrets: inherit

  epac-deployPolicy:
      if: ${{ needs.epac-build.outputs.CREATED_POL_PLAN == 'true' }}
      name: epac deploy policy
      needs: [epac-build, preConfig]
      permissions:
          id-token: write
          contents: read
          pull-requests: write
      uses: ./.github/workflows/job-epac-deployPolicy.yml
      with:
        definitionsRootFolder: ${{ needs.preConfig.outputs.definitionsRootFolder }}
        pacEnvironment: ${{ needs.preConfig.outputs.pacEnvironment }}
        planFolder: ${{ needs.preConfig.outputs.planFolder }}
        epac_pinned_version: ${{ needs.preConfig.outputs.epac_pinned_version }}
        az_version: ${{ needs.preConfig.outputs.az_version }}
        azAccounts_version: ${{ needs.preConfig.outputs.azAccounts_version }}
        azResources_version: ${{ needs.preConfig.outputs.azResources_version }}
        azResourceGraph_version: ${{ needs.preConfig.outputs.azResourceGraph_version }}
      secrets: inherit

  epac-deployRoles:
      name: epac deploy policy
      needs: [epac-deployPolicy, epac-build, preConfig]
      permissions:
          id-token: write
          contents: read
          pull-requests: write
      uses: ./.github/workflows/job-epac-deployRoles.yml
      with:
        definitionsRootFolder: ${{ needs.preConfig.outputs.definitionsRootFolder }}
        pacEnvironment: ${{ needs.preConfig.outputs.pacEnvironment }}
        planFolder: ${{ needs.preConfig.outputs.planFolder }}
        epac_pinned_version: ${{ needs.preConfig.outputs.epac_pinned_version }}
        az_version: ${{ needs.preConfig.outputs.az_version }}
        azAccounts_version: ${{ needs.preConfig.outputs.azAccounts_version }}
        azResources_version: ${{ needs.preConfig.outputs.azResources_version }}
        azResourceGraph_version: ${{ needs.preConfig.outputs.azResourceGraph_version }}
      secrets: inherit
