name: Run on PR Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "event action ${{ github.event.action }}" 
        run: 
          echo "The event type is ${{ github.event.action }}" 
          echo "PR merged? ${{ github.event.pull_request.merged}}"
      - name: "run git"
        run: git branch -r
      - name: "PR echo branch name ${{ github.head_ref }}"
        run: echo "Branch name is ${{ github.head_ref }}"
  run_if:
    if: contains(github.head_ref, 'run')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'main/'"
      - run: echo "Branch name is ${{ github.head_ref }}"
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        echo "Branch name is ${{ github.head_ref }}"
