# .github/workflows/vending-request-processor-workflow.yml
name: Vending Request Processor Workflow

on:
  workflow_call:
    inputs:
      gh_environment:
        required: true
        type: string

jobs:
  processor:
    name: Run Vending Request Processor
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3