# .github/workflows/vending-request-processor-workflow.yml
name: Vending Request Processor Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'workloads/requests/**'
  workflow_dispatch:
    inputs:
      request_id:
        required: true
        default: 'wBurgers'
        description: 'The vending request ID to be processed.'

jobs:
  processor-yml:
    name: Generate Vending YAML Files
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: sbx
    outputs:
      request_id: ${{ steps.parse-id.outputs.request_id }}
    steps:
      - name: Set Request ID
        id: parse-id
        shell: pwsh
        run: |
          $requestPath = $env:REQUEST_PATH
          $requestId = $requestPath.split("/")[-1]
          echo "Request ID: $requestId"
          echo "request_id=$requestId" >> $env:GITHUB_OUTPUT
          echo "REQUEST_ID=$requestId" >> $env:GITHUB_ENV
        env:
          REQUEST_PATH: ${{ github.head_ref || inputs.request_id }}
      - name: Generate YAML Files
        shell: pwsh
        run: |
          $requestId = $env:REQUEST_ID
          echo "Generating YAML for request $requestId..."
      - name: Upload Vending Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vending-request-${{ env.REQUEST_ID }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/workloads/requests/${{ env.REQUEST_ID }}/*.json
            ${{ github.workspace }}/workloads/subscriptions/${{ env.REQUEST_ID }}/*.yml
            ${{ github.workspace }}/workloads/builds/${{ env.REQUEST_ID }}/*.yml
