# .github/workflows/vending-request-processor-workflow.yml
name: Vending Request Processor Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'workloads/requests/**'
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'workloads/requests/**'
  workflow_dispatch:  

jobs:
  processor-yml:
    name: Generate Vending YAML Files
    runs-on: ubuntu-latest
    environment: sbx
    steps:
      - name: Details
        run: |
          echo "Start creating YAML files..."
          echo "Github.ref: $GITHUB_REF"
          echo "Github.event_name: $GITHUB_EVENT_NAME"
          echo "Github.event_path: $GITHUB_EVENT_PATH"
          echo "Github.event: $GITHUB_EVENT"
          echo "Github.ref: ${{github.ref}}"
          echo "Github.event_name: ${{github.event_name}}"
          echo "Github.event_path: ${{github.event_path}}"
          echo "Github.event: ${{github.env}}"
          echo "Github.base_ref: ${{github.base_ref}}"
          echo "Github.head_ref: ${{github.head_ref}}"
          echo "Github.ref_name: ${{github.ref_name}}"
          echo "Github.action_ref: ${{github.action_ref}}"
          echo "Github.head_commit.message: ${{github.event.head_commit.message}}"
          echo "Github.event.base_ref: ${{github.event.base_ref}}"
          $commitMessage="${{github.event.head_commit.message}}"
          $requestId = $commitMessage.split("/")[-1]
          echo "Request ID: $requestId"
        shell: pwsh
  processor-yml-merged:
    name: Generate Vending YAML Files if PR is Merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: sbx
    steps:
      - name: Details
        shell: pwsh
        run: |
          echo "Start creating YAML files..."
          echo "Github.ref: $GITHUB_REF"
          echo "Github.event_name: $GITHUB_EVENT_NAME"
          echo "Github.event_path: $GITHUB_EVENT_PATH"
          echo "Github.event: $GITHUB_EVENT"
          echo "Github.ref: ${{github.ref}}"
          echo "Github.event_name: ${{github.event_name}}"
          echo "Github.event_path: ${{github.event_path}}"
          echo "Github.base_ref: ${{github.base_ref}}"
          echo "Github.head_ref: ${{github.head_ref}}"
          echo "Github.event.pull_request.head.ref: "${{github.event.pull_request.head.ref}}"
          echo "Github.event.pull_request.base.label: "${{github.event.pull_request.base.label}}"
          echo "Github.ref_name: ${{github.ref_name}}"
          echo "Github.action_ref: ${{github.action_ref}}"          
          echo "Github.head_commit.message: ${{github.event.head_commit.message}}"          
          $prBranch = "${{github.head_ref}}"
          $requestId = $prBranch.split("/")[-1]
          echo "Request ID: $requestId"
